### ISSUE TITLE
<kbd>&uarr;</kbd>, <kbd>&darr;</kbd>, <kbd>Ctrl</kbd>+<kbd>r</kbd>

### ISSUE THREAD

**Issue by kangwon-naver** [kangwonlee/tutorial#22]
https://github.com/kpumecpf/2009class/issues/24

**Comment by kangwonlee** [comment]
* 00 in ipynb
* edit on github limited

**Comment by kangwonlee** [comment]
* c787ac1f  already had <kbd>Ctrl</kbd>+<kbd>r</kbd>
* now 7e5893bb49950a43bde735fc220eafb4c9321912 has <kbd>&uarr;</kbd>, <kbd>&darr;</kbd> with examples
